// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PandoLogic.Data;

namespace PandoLogic.Migrations
{
    [DbContext(typeof(JobViewsContext))]
    [Migration("20220510192724_AddTables")]
    partial class AddTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.16");

            modelBuilder.Entity("PandoLogic.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime")
                        .HasColumnName("creation_time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.HasKey("Id");

                    b.ToTable("jobs");
                });

            modelBuilder.Entity("PandoLogic.Models.View", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("ViewDate")
                        .HasColumnType("datetime")
                        .HasColumnName("view_date");

                    b.Property<int>("job_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("job_id");

                    b.ToTable("views");
                });

            modelBuilder.Entity("PandoLogic.Models.View", b =>
                {
                    b.HasOne("PandoLogic.Models.Job", "Job")
                        .WithMany("Views")
                        .HasForeignKey("job_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("PandoLogic.Models.Job", b =>
                {
                    b.Navigation("Views");
                });
#pragma warning restore 612, 618
        }
    }
}
